server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    # ğŸ‘‡ ä¿®æ”¹ç‚¹ 1: ç«¯å£ä» 3306 æ”¹æˆ 1314
    # ğŸ‘‡ ä¿®æ”¹ç‚¹ 2: æ•°æ®åº“åä» test æ”¹æˆ review (å¦‚æœä½ åˆšæ‰å»ºåº“ç”¨çš„åå­—æ˜¯ review)
    source: root:root1234@tcp(127.0.0.1:1314)/review?parseTime=True&loc=Local
  redis:
    # ğŸ‘‡ ä¿®æ”¹ç‚¹ 3: ç«¯å£ä» 6379 æ”¹æˆ 1592
    addr: 127.0.0.1:1592
    read_timeout: 0.2s
    write_timeout: 0.2s
snowflake:
  start_time: "2025-12-25" # 2023-10-01 00:00:00 UTC çš„æ—¶é—´æˆ³
  machine_id: 1